type Picture = {
  id: string;
  title: string;
  description: string;
  available?: boolean;
  owner?: string;
};

export const pictures: Picture[] = [
  {
    id: "01",
    title: "Desert Island Shipwreck",
    description: 'Water Colour 30" x 20"',
  },
  {
    id: "02",
    title: "Dreams of Erotica",
    description: 'Water Colour 35" x 20"',
  },
  { id: "03", title: "The Pillagers", description: 'Water Colour 19" x 25"' },
  {
    id: "04",
    title: "Flight of The Albatros",
    description: 'Water Colour 22" x 29"',
  },
  {
    id: "05",
    title: "Gemini Meets Aquarius",
    description: 'Oil Colour 24" x 36"',
  },
  {
    id: "06",
    title: "In Search of My Pegasus",
    description: 'Water Colour 20" x 23"',
  },

  {
    id: "08",
    title: "Mindscape from the Temple of Love",
    description: 'Water Colour 30" x 40"',
  },
  {
    id: "09",
    title: "On The Verge of a Dream",
    description: 'Oil Colour  48" x 42"',
  },
  {
    id: "10",
    title: "Prayer For Philomena",
    description: 'Water Colour 20" x 27"',
  },
  { id: "11", title: "Primary Shapes", description: 'Water Colour 27" x 20"' },
  {
    id: "12",
    title: "Return of the Argonauts",
    description: 'Water Colour 41" x 29"',
  },
  {
    id: "13",
    title: "Rock and Roller-Coaster Revisited",
    description: 'Water Colour 22" x 29"',
  },
  {
    id: "14",
    title: "Rock and Roller-Coaster",
    description: 'Water Colour 22" x 29"',
  },
  { id: "15", title: "Small Wonder II", description: 'Water Colour 19" x 32"' },
  { id: "16", title: "Small Wonder", description: 'Water Colour 19" x 32"' },
  {
    id: "17",
    title: "Parable of the Puritones &amp; Optimyths",
    description: 'Oil Colour 36" x 26"',
  },
  {
    id: "19",
    title: "Space Lab Disaster",
    description: 'Water Colour 27" x 20"',
  },
  { id: "20", title: "The Birthstone", description: 'Water Colour 36" x 20"' },
  {
    id: "21",
    title: "The Fallen Eagles",
    description: 'Water Colour 22" x 29"',
  },
  {
    id: "22",
    title: "The Love or Why Leaf",
    description: 'Water Colour 28" x 19"',
  },
  { id: "23", title: "The Reeper", description: 'Water Colour 34" x 21"' },
  {
    id: "24",
    title: "The Evolution of Peace",
    description: 'Oil Colour 35" x 48"',
  },
  {
    id: "25",
    title: "The Timegame Backwards",
    description: 'Oil Colour 24" x 24"',
  },
  { id: "26", title: "The Troubles", description: 'Water Colour 35" x 19"' },
  {
    id: "27",
    title: "Three Pieces of Mind",
    description: 'Oil Colour 24" x 40"',
  },
  { id: "28", title: "Dali's Ka", description: 'Water Colour 17" x 22"' },
  {
    id: "29",
    title: "Dali's Ka Revisited",
    description: 'Oil Colour 23" x 29"',
  },
  {
    id: "30",
    title: "In The Golden Rains",
    description: 'Oil Colour 25" x 39"',
  },
  {
    id: "32",
    title: "Mindscape from the 7th Level",
    description: 'Oil Colour 24" x 36"',
  },
  {
    id: "33",
    title: "Human Cenotaph to the Earth",
    description: 'Water Colour 35" x 29"',
  },
  {
    id: "34",
    title: "The Evolution of Peace II",
    description: 'Oil Colour 35" x 47"',
  },
  {
    id: "35",
    title: "The Creatures Who Forever Sleep",
    description: 'Oil Colour 18" x 42"',
  },
  {
    id: "37",
    title: "Galileo (Jupiter Mission)",
    description: 'Oil Colour 40" x 24"',
  },
  {
    id: "39",
    title: "Paradise Opens Tomorrow",
    description: 'Oil Colour 28" x 36"',
  },
  {
    id: "41",
    title: "The Jazz Machine Revisited",
    description: 'Water Colour 22" x 30"',
  },
  {
    id: "42",
    title: "Blues Machine Returns with Love",
    description: 'Oil Colour 20" x 38"',
  },
  {
    id: "43",
    title: "A Thing O' Purpose",
    description: 'Water Colour 23" x 20"',
  },
  {
    id: "1O0A6266",
    title: "Little Boy Blue Come Tickle Your Brain",
    description: 'Oil Colour 17" x 43"',
    available: false,
    owner: "Kane & Lydia",
  },
  {
    id: "45",
    title: "Variations on a theme by Leonardo",
    description: 'Water Colour  19" diameter',
  },
  {
    id: "46",
    title: "The Alchemists Puzzle",
    description: 'Water Colour  19" x 15"',
  },
  { id: "47", title: "Sunrise", description: 'Water Colour  22" x 22"' },
  { id: "48", title: "Thought Waves", description: 'Water Colour  23" x 17"' },
  {
    id: "49",
    title: "LOVE - The Universal Organ Recital",
    description: "Oil Colour",
  },
  { id: "50", title: "Sunset", description: "Water Colour" },
  { id: "52", title: "Baptism of Fire", description: 'Water Colour 26" x 22"' },
  {
    id: "53",
    title: "Smoke and Mirrors",
    description: 'Water colour 24" x 20"',
  },
  { id: "54", title: "The Sane Fishers", description: 'Oil Colour 44" x 24"' },
  {
    id: "55",
    title: "Yesterday's History",
    description: 'Water Colour 22" x 29"',
  },
  {
    id: "56",
    title: "Today's a Gift (that's why we call it the present)",
    description: 'Water Colour 22" x 29"',
  },
  {
    id: "57",
    title: "Tomorrow's a Mystery",
    description: 'Water Colour 22" x 29"',
  },
  { id: "58", title: "Dream Flight", description: 'Water Colour 30" x 23"' },
  {
    id: "59",
    title: "Your Memory Is Your Bible, Your Imagination Your Future",
    description: 'Oil Colour 23" x 23" 1967',
  },
  { id: "60", title: "Love Machine", description: 'Water Colour 20" x 28"' },
  { id: "61", title: "The Guardians", description: 'Water Colour 12" x 18"' },
  {
    id: "62",
    title: "In the Golden Rains Revisited",
    description: 'Water Colour 24" x 20"',
  },
  {
    id: "63",
    title: "Food for Thought",
    description: 'Water Colour 20" x 14"',
  },
  {
    id: "64",
    title: "More Food For Thought",
    description: 'Water Colour 20" x 13"',
  },
  { id: "65", title: "The Magic Box", description: 'Water Colour 22" x 29"' },
  { id: "66", title: "The Magic Ball", description: 'Water Colour 22" x 29"' },
  {
    id: "67",
    title: "The Wishing Star",
    description: 'Water Colour 22" x 29"',
  },
  // {
  //   id: "69",
  //   title: "Temple of Love Revisited",
  //   description: 'Water Colour 22" x 30"',
  // },
  { id: "70", title: "The Marble Run", description: 'Water Colour 20" x 28"' },
  {
    id: "71",
    title: "Fire Nymphs",
    description: 'Water Colour 22" x 22"',
    owner: "Bethan Hunt",
  },
  {
    id: "72",
    title: "When we were Young",
    description: 'Water Colour 21.5" x 29 1/4"',
  },
  {
    id: "73",
    title: "Family Outing",
    description: 'Water Colour 17" x 23"',
  },
  {
    id: "74",
    title: "Your Imagination is Your Future",
    description: 'Water Colour 19.5" x 19.5"',
  },
  {
    id: "75",
    title: "Mindscape from the Eighth Level",
    description: 'Water Colour 22" x 29"',
  },
  {
    id: "1O0A6320",
    title: "The Coming",
    description: 'Airbrush Water Colour 20" x 29" 1987',
    available: false,
    owner: "Kane & Lydia",
  },
  {
    id: "1O0A6260",
    title: "The Mating Ritual of the Metal and the Femetal",
    description: 'Oil Colour 25" x 25" 1967',
    available: false,
    owner: "Kane & Lydia",
  },
  {
    id: "1O0A6283",
    title: "The Order of Chaos",
    description: "Airbrush Water Colour, 1985",
    available: true,
  },
  {
    id: "1O0A6263",
    title: "The Colour and I",
    description: 'Oil Colour 24" x 36"',
    available: false,
    owner: "Dave & Sarah Gilliver",
  },
  {
    id: "1O0A6294",
    title: "Victor U",
    description: "Airbrush Water Colour, 1988",
    available: false,
    owner: "Emily & Leo Woodfelder",
  },
  {
    id: "1O0A6329",
    title: "Untitled 2",
    description: "Ink on Paper",
    available: false,
    owner: "Andrew Dowling",
  },
  {
    id: "1O0A6261",
    title: "Look",
    description: 'Oil Colour 26" x 38", 1984',
    available: true,
  },
  {
    id: "1O0A6264",
    title: "Firebird",
    description: 'Oil Colour, 31" x 42" 1995',
    available: false,
    owner: "Vicky & Theo Scholes",
  },
  {
    id: "1O0A6309",
    title: "In the Light of New Through the Light of Old",
    description: 'Water Colour 23" x 34" 1970',
    available: true,
  },
  {
    id: "1O0A6332",
    title: "Platinum - Blood Sweat and Tears",
    description: "1989",
    available: true,
  },
  {
    id: "1O0A6287",
    title: "Untitled 1",
    description: "Airbrush Water Colour, 1985",
    available: true,
  },
  {
    id: "1O0A6295",
    title: "Echo Kilo",
    description: "Airbrush Water Colour, 1985",
    available: false,
    owner: "Mark Horne",
  },
  {
    id: "1O0A6286",
    title: "Recorded Live",
    description: "1985",
    available: true,
  },
  {
    id: "1O0A6296",
    title: "Simplicity of Conscience",
    description: "1966",
    available: false,
    owner: "Valpuri & Richard Howe",
  },
  {
    id: "1O0A6297",
    title: "The Dragon Family",
    description: "2015",
    available: false,
    owner: "Nick & Helen Rowles",
  },
  {
    id: "1O0A6298",
    title: "Love Machine",
    description: "2016",
    available: true,
  },
  {
    id: "1O0A6299",
    title: "Glider",
    description: 'Water Colour 29" x 37" 2014',
    available: false,
    owner: "Nick Auluck",
  },
  {
    id: "1O0A6306",
    title: "Primary Shapes (Alchemy)",
    description: "Airbrush Water Colour, 2000",
    available: true,
  },
  {
    id: "1O0A6307",
    title: "In Search of the Promised Land",
    description: 'Water Colour 29"x 22" 2004',
    available: false,
    owner: "Ben Thiele",
  },
  {
    id: "1O0A6308",
    title: "K for Kitty",
    description: "Airbrush Water Colour, 1994",
    available: false,
    owner: "Mark Brady",
  },
  {
    id: "1O0A6312",
    title: "Highland Dream",
    description: "1996",
    available: false,
    owner: "Fay & Marc Constantine",
  },
  {
    id: "1O0A6314",
    title: "Talisman",
    description: "Airbrush Water Colour, 1990",
    available: false,
    owner: "Gill & Richard Gale",
  },
  {
    id: "1O0A6315",
    title: "Temple of Love Revisited",
    description: 'Water Colour 22" x 30" 2020',
    available: false,
    owner: "Cat O'Neil",
  },
  {
    id: "1O0A6323",
    title: "Taming the Hounds of Aries",
    description: 'Airbrush Water Colour 26" x 22" 2008',
    available: true,
  },
  {
    id: "1O0A6324",
    title: "A Thing O'Beauty",
    description: "2016",
    available: false,
    owner: "Rachel Bywater & Kathy Sawkins",
  },
  {
    id: "1O0A6325",
    title: "Post Morphman",
    description: 'Oil Colour 15" x 22" 1966',
    available: true,
  },
  {
    id: "1O0A6326",
    title: "Total Eclipse of our Son",
    description: 'Water Colour 20" x 25" 1981',
    available: false,
    owner: "Collette Walker",
  },
  {
    id: "1O0A6327",
    title: "Sparrowhawk",
    description: 'Water Colour 21" x 14" 2019',
    available: false,
    owner: "Gill & Richard Gale",
  },
  {
    id: "1O0A6328",
    title: "Departures Hall for the Promised Land",
    description: "",
    available: false,
    owner: "Simon P Scarlet",
  },
  {
    id: "1O0A6330",
    title: "Chrizlam Subliminal Sky",
    description: "2008",
    available: false,
    owner: "Phoebe Gale & Tom Hughes",
  },
  {
    id: "1O0A6333",
    title: "Dali's Duck (Red Snail in the Sunset)",
    description: "2016",
    available: true,
  },
  {
    id: "1O0A6334",
    title: "From Heaven to Earth",
    description: "1972",
    available: true,
    // Emily wants if nobody else having
  },
  {
    id: "1O0A6335",
    title: "The Surnaturalist Observer",
    description: "1972",
    available: false,
    owner: "Kane & Lydia",
  },
  {
    id: "1O0A6336",
    title: "The Tree of Want",
    description: "",
    available: false,
    // owner: "Emily & Leo Woodfelder",
  },
  {
    id: "1O0A6338",
    title: "Nursery School",
    description: '21" x 30" 1985',
    available: true,
  },
  {
    id: "1O0A6339",
    title: "Untitled 3",
    description: '21" x 30" 1985',
    available: true,
  },
];
